language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install .

script:
  - python setup.py test

deploy:
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = 3.6
  provider: pypi
  user: "migurski"
  password:
    secure: "aM9ue+TWXMYh3KM3gGHXpXtBuFx6tn41l+n6gLa8qgo0EhwGV0RwZ8Yrz8bSePU7F+Pe7fhMR+jrW22LkdK4+f8xv/gG03Exm9tzr+WMmCBMnVlu8xsgQKTaIah0hIFwfYU6X8FOW5dLd7izhGH39eth2pqxX8+aw8YWny0GueP6KdQ8nYpr1igAvtksY92uuz/t6p9jDFljTQkFAD8NJdqrH2ILdjwbjyJ4gwCmpqBdkyWtumzOlf2mubEwTBnDJS3+usXQPeSq+hH7ckLnEf9lhDl13fay0OeS7pr+hnEwaeh9RU95C4N0055tEinQn4fTheAYVHO50UvUlwH3o0uWqieMMqjCMIAvgy/gGfnMiu60cZVIOnc3zhIOW8tyXaTjrPJ0VHbywbJ/YEDnIje8Ofq9jFRvLnqugyNwzoLvAPzuRtiv8rrCX9Khaihidoy0ZyB4A005W8+XtHGx9knU4PqFUcnj8WfqSwGS11pg4Ty+dlCaQ2GfQQOYhZzkhxu2Am6zmZ6robMJfz8Pyv8Shh+hdA9qKJUWZoz2u2lT4lj/Uczc/ucXDfjLlZvwP3MwcoBKlSFIOuRLDnl+Tt1MguUr4hQZfuoXZCMrAh2UACeKlQdbTJtMJzRFE1hp38bWM0wDVEkyXWZxt/kX+aUJaQI7ZIt6biELfIDEyPM="
